version: '3.1'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: central_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: city_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d city_db -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  central:
    image: stanisica/cc-central
    container_name: central
    restart: always
    depends_on:
      mysql_db:
        condition: service_healthy

  ns:
    image: stanisica/cc-city
    container_name: ns
    restart: always
    ports:
      - 8081:8081
    depends_on:
      postgres_db:
        condition: service_healthy

volumes:
  mysql_data:
  postgres_data:
