version: "3.1"

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: central_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db_ns:
    image: postgres:latest
    container_name: postgres_db_ns
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: city_db
    volumes:
      - postgres_data_ns:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d city_db -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db_bg:
    image: postgres:latest
    container_name: postgres_db_bg
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: city_db
    volumes:
      - postgres_data_bg:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d city_db -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_db_nis:
    image: postgres:latest
    container_name: postgres_db_nis
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
      POSTGRES_DB: city_db
    volumes:
      - postgres_data_nis:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d city_db -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  central:
    image: stanisica/cc-central:latest
    container_name: central
    restart: always
    depends_on:
      mysql_db:
        condition: service_healthy

  ns:
    image: stanisica/cc-city:latest
    container_name: ns
    restart: always
    ports:
      - 8081:8081
    environment:
      POSTGRES_CONNECTION: postgres_db_ns
    depends_on:
      postgres_db_ns:
        condition: service_healthy

  bg:
    image: stanisica/cc-city:latest
    container_name: bg
    restart: always
    ports:
      - 8082:8081
    environment:
      POSTGRES_CONNECTION: postgres_db_bg
    depends_on:
      postgres_db_bg:
        condition: service_healthy

  nis:
    image: stanisica/cc-city:latest
    container_name: nis
    restart: always
    ports:
      - 8083:8081
    environment:
      POSTGRES_CONNECTION: postgres_db_nis
    depends_on:
      postgres_db_nis:
        condition: service_healthy

volumes:
  mysql_data:
  postgres_data_ns:
  postgres_data_bg:
  postgres_data_nis:
