#NS
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-ns
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-ns"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-pvc-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

#BG
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-bg
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-bg"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-pvc-bg
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi

#NIS
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-nis
spec:
  capacity:
    storage: 256Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres-nis"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc-nis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
